const actionTypes = {
    "CLEAR_POSITION" : "CLEAR_POSITION",
    "NEW_MOVE" : "NEW_MOVE",
    "GENERATE_POSSIBLE_MOVES" : "GENERATE_POSSIBLE_MOVES",
    "PROMOTION_POP" : "PROMOTION_POP",
    "CONTINUE_GAME" : "CONTINUE_GAME",
    "DISABLE_CASTLE" : "DISABLE_CASTLE",
    "CHECK_MATE" : "CHECK_MATE",
    "STALEMATE" : "STALEMATE",
    "START_GAME" : "START_GAME",
    "FLIP_BOARD" : "FLIP_BOARD",
    "SETUP" : "SETUP",
    "INSUFFICIENT" : "INSUFFICIENT"
}

export default actionTypes